// <auto-generated />
using System;
using InventorySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySystem.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20250729151635_AddBomSupportToItemDocuments")]
    partial class AddBomSupportToItemDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InventorySystem.Models.Bom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BaseBomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedFromChangeOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentBomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionHistory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseBomId");

                    b.HasIndex("CreatedFromChangeOrderId");

                    b.HasIndex("ParentBomId");

                    b.ToTable("Boms");
                });

            modelBuilder.Entity("InventorySystem.Models.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceDesignator")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("ItemId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("InventorySystem.Models.ChangeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseBomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactAnalysis")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImplementedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewBomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NewItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseBomId");

                    b.HasIndex("BaseItemId");

                    b.HasIndex("NewBomId");

                    b.HasIndex("NewItemId");

                    b.ToTable("ChangeOrders");
                });

            modelBuilder.Entity("InventorySystem.Models.ChangeOrderDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DocumentData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeOrderId");

                    b.ToTable("ChangeOrderDocuments");
                });

            modelBuilder.Entity("InventorySystem.Models.FinishedGood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("FinishedGoods");
                });

            modelBuilder.Entity("InventorySystem.Models.InventoryAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjustedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostImpact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAdjusted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryAdjustments");
                });

            modelBuilder.Entity("InventorySystem.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedFromChangeOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredVendor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionHistory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseItemId");

                    b.HasIndex("CreatedFromChangeOrderId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventorySystem.Models.ItemDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DocumentData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_ItemDocument_ItemOrBom", "(ItemId IS NOT NULL AND BomId IS NULL) OR (ItemId IS NULL AND BomId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinishedGoodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OverheadCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityProduced")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("FinishedGoodId");

                    b.HasIndex("ProductionDate");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("InventorySystem.Models.ProductionConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConsumedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCostAtConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProductionId");

                    b.ToTable("ProductionConsumptions");
                });

            modelBuilder.Entity("InventorySystem.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemVersionReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemVersionReferenceId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DocumentData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseDocuments");
                });

            modelBuilder.Entity("InventorySystem.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleDate");

                    b.HasIndex("SaleNumber")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("InventorySystem.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinishedGoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FinishedGoodId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", t =>
                        {
                            t.HasCheckConstraint("CK_SaleItem_ItemOrFinishedGood", "(ItemId IS NOT NULL AND FinishedGoodId IS NULL) OR (ItemId IS NULL AND FinishedGoodId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Bom", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "BaseBom")
                        .WithMany("Versions")
                        .HasForeignKey("BaseBomId");

                    b.HasOne("InventorySystem.Models.ChangeOrder", "CreatedFromChangeOrder")
                        .WithMany()
                        .HasForeignKey("CreatedFromChangeOrderId");

                    b.HasOne("InventorySystem.Models.Bom", "ParentBom")
                        .WithMany("SubAssemblies")
                        .HasForeignKey("ParentBomId");

                    b.Navigation("BaseBom");

                    b.Navigation("CreatedFromChangeOrder");

                    b.Navigation("ParentBom");
                });

            modelBuilder.Entity("InventorySystem.Models.BomItem", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "Bom")
                        .WithMany("BomItems")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany("BomItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventorySystem.Models.ChangeOrder", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "BaseBom")
                        .WithMany()
                        .HasForeignKey("BaseBomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventorySystem.Models.Item", "BaseItem")
                        .WithMany()
                        .HasForeignKey("BaseItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventorySystem.Models.Bom", "NewBom")
                        .WithMany()
                        .HasForeignKey("NewBomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventorySystem.Models.Item", "NewItem")
                        .WithMany()
                        .HasForeignKey("NewItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseBom");

                    b.Navigation("BaseItem");

                    b.Navigation("NewBom");

                    b.Navigation("NewItem");
                });

            modelBuilder.Entity("InventorySystem.Models.ChangeOrderDocument", b =>
                {
                    b.HasOne("InventorySystem.Models.ChangeOrder", "ChangeOrder")
                        .WithMany("ChangeOrderDocuments")
                        .HasForeignKey("ChangeOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeOrder");
                });

            modelBuilder.Entity("InventorySystem.Models.FinishedGood", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "Bom")
                        .WithMany()
                        .HasForeignKey("BomId");

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("InventorySystem.Models.InventoryAdjustment", b =>
                {
                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventorySystem.Models.Item", b =>
                {
                    b.HasOne("InventorySystem.Models.Item", "BaseItem")
                        .WithMany("Versions")
                        .HasForeignKey("BaseItemId");

                    b.HasOne("InventorySystem.Models.ChangeOrder", "CreatedFromChangeOrder")
                        .WithMany()
                        .HasForeignKey("CreatedFromChangeOrderId");

                    b.Navigation("BaseItem");

                    b.Navigation("CreatedFromChangeOrder");
                });

            modelBuilder.Entity("InventorySystem.Models.ItemDocument", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "Bom")
                        .WithMany("Documents")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany("DesignDocuments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bom");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventorySystem.Models.Production", b =>
                {
                    b.HasOne("InventorySystem.Models.Bom", "Bom")
                        .WithMany()
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.FinishedGood", "FinishedGood")
                        .WithMany("Productions")
                        .HasForeignKey("FinishedGoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("FinishedGood");
                });

            modelBuilder.Entity("InventorySystem.Models.ProductionConsumption", b =>
                {
                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.Production", "Production")
                        .WithMany("MaterialConsumptions")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("InventorySystem.Models.Purchase", b =>
                {
                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.Item", "ItemVersionReference")
                        .WithMany()
                        .HasForeignKey("ItemVersionReferenceId");

                    b.Navigation("Item");

                    b.Navigation("ItemVersionReference");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseDocument", b =>
                {
                    b.HasOne("InventorySystem.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDocuments")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("InventorySystem.Models.SaleItem", b =>
                {
                    b.HasOne("InventorySystem.Models.FinishedGood", "FinishedGood")
                        .WithMany("SaleItems")
                        .HasForeignKey("FinishedGoodId");

                    b.HasOne("InventorySystem.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("InventorySystem.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishedGood");

                    b.Navigation("Item");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("InventorySystem.Models.Bom", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("Documents");

                    b.Navigation("SubAssemblies");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InventorySystem.Models.ChangeOrder", b =>
                {
                    b.Navigation("ChangeOrderDocuments");
                });

            modelBuilder.Entity("InventorySystem.Models.FinishedGood", b =>
                {
                    b.Navigation("Productions");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("InventorySystem.Models.Item", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("DesignDocuments");

                    b.Navigation("Purchases");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InventorySystem.Models.Production", b =>
                {
                    b.Navigation("MaterialConsumptions");
                });

            modelBuilder.Entity("InventorySystem.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDocuments");
                });

            modelBuilder.Entity("InventorySystem.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
